### ISSUE TITLE
Error in string slicing

### ISSUE THREAD

**Issue by Mnw2212** [rahul080327/medusa#53]
String slicing goes wrong almost every time.Seems like it needs re-implementation.

**Comment by rahul080327** [comment]
@apoorv2404 can have a look in this?

**Comment by apoorv2404** [comment]
Will have a look at this today

**Comment by apoorv2404** [comment]
Could you let me know the test cases where it is failing because at the time of writing me and you tested it to the best of our knowledge. It may be some behavior of python that we may not be aware of and hence would not have implemented the way it was meant to be.

**Comment by rahul080327** [comment]
@Mnw2212 will be better at this?

**Comment by Mnw2212** [comment]
I am un

**Comment by Mnw2212** [comment]
I am unable to find the test cases where this failed. I think it will be appropriate to close this issue until I get hold of those test cases again.
@rahul080327
