### ISSUE TITLE
'1' is False in Dart and True in Python

### ISSUE THREAD

**Issue by Mnw2212** [rahul080327/medusa#55]
This code doesnt work.
```python
    if(1):
        print "Works"
    else:
        print "It doesnt"
```

```
output ( python ) : Works
output ( medusa ) : It doesnt
```
Reference. : Dart up and running (page 18)
Dart in the production mode does not accept 1 as True since the condition is not strictly "True", it takes it to be false and prints the statements under else.
Difficult to handle. May pose a problem in large python libraries.

**Comment by rahul080327** [comment]
Need to fix the test node of the if module.

**Comment by rahul080327** [comment]
Fixed it.
