### ISSUE TITLE
Error while testing medusa.

### ISSUE THREAD

**Issue by AmNotGod** [rahul080327/medusa#59]
My test code:
-----------------------------------------------------------------------------------------------
import time
start_time = time.time()
for i in range(1000000):
    print i
end_time = time.time()
print "\n\n--------------\n%d seconds\n" % (end_time-start_time)
-----------------------------------------------------------------------------------------------

Error:
-------------------------------------------------------------------------------------------------
'file:///home/qingxin/WorkSpace/test.dart': error: line 1 pos 298: unterminated string literal
import'file:////home/qingxin/.medusa/lib/pytime.dart';import'file:////home/qingxin/.medusa/lib/inbuilts.dart';import'dart:io';var time=new $PyTime();var start_time,end_time;main(){start_time=time.time();for(var i in range($n(1000000))){stdout.writeln(i);}end_time=time.time();stdout.writeln((str('
--------------------------------------------------------------------------------------------------

I can't figure out why, is there something wrong with my settings?

**Comment by rahul080327** [comment]
Yes, this is a bug in the string formatting module of medusa. Instead of printing the \n its literally adding a newline. Looking into it.

**Comment by AmNotGod** [comment]
Thanks, I get it.
But can this bug be fixed?

**Comment by rahul080327** [comment]
Yes. I'm onto it. Also the time module you are using is not properly ported to dart in medusa. See the pytime.dart file for more info. I'm pretty sure the end time calculation would be wrong.

**Comment by AmNotGod** [comment]
Yes you are right, but you have done a good job, thanks!

**Comment by rahul080327** [comment]
:D Thanks. Porting the insanely huge py libs to dart is a big hassle specially most of them being native. Need help there mostly.

**Comment by rahul080327** [comment]
Also you can format the generated dart code by using dartfmt <dart file>. Formatted output will be on STDOUT.

**Comment by rahul080327** [comment]
Its Fixed.

**Comment by AmNotGod** [comment]
Thanks. 
I am a freshman of the school of software.Currently, I need to program with python for my homework. However, I am really a beginner. 
I will offer my help when I am ready, there is still a long way to go...

**Comment by rahul080327** [comment]
Thanks! :D
